### ISSUE TITLE
Browserless on docker crash idk why.

### ISSUE THREAD

**Issue by EliotFR44** [browserless/browserless#3618]
Hi,

This Saturday I wanted to test browserless on docker.
It crashes but I don't know why T_T

 

 

My browserless.yaml : 
```dockerfile
version: "3.8"
services:
  browserless0:
    container_name: browserless0
    image: browserless/chrome
    ports: 
      - "3000:3000"
    restart: always
    environment:
      - MAX_CONCURRENT_SESSIONS=1
      - CONNECTION_TIMEOUT=35000
      - MAX_QUEUE_LENGTH=5
      - ENABLE_CORS=true
      - ENABLE_XVBF=true
      - EXIT_ON_HEALTH_FAILURE=true
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - CHROME_REFRESH_TIME=3600000
      - DEFAULT_BLOCK_ADS=false
      - DEFAULT_STEALTH=true
      - DEFAULT_HEADLESS=false
      - DEFAULT_LAUNCH_ARGS=["--window-size=1920,1080","--proxy-server=socks5://192.168.1.140:1078"]
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - DEFAULT_IGNORE_DEFAULT_ARGS=false
      - DISABLED_FEATURES=["downloadEndpoint","functionEndpoint","pdfEndpoint","screencastEndpoint","scrapeEndpoint","statsEndpoint","workspaces"]
      - FUNCTION_ENABLE_INCOGNITO_MODE=true 
 
``` 

i run it with : 
`docker compose -f browserless.yaml up  --remove-orphans`

it looks to start normaly : 
```
eliot@chrysapileradieux:~/browserless$ docker compose -f browserless.yaml up  --remove-orphans
[+] Running 3/0
 ✔ Network browserless_default  Created                                                                                                                                                                                                 0.1s
 ✔ Container browserless50      Removed                                                                                                                                                                                                 0.0s
 ✔ Container browserless0       Created                                                                                                                                                                                                 0.0s
Attaching to browserless0
browserless0  | 2023-10-21T12:39:48.167Z browserless:server Using configuration:
browserless0  | 2023-10-21T12:39:48.169Z browserless:server {
browserless0  |   CONNECTION_TIMEOUT: 35000,
browserless0  |   MAX_CONCURRENT_SESSIONS: 1,
browserless0  |   QUEUE_LENGTH: 5,
browserless0  |   SINGLE_RUN: false,
browserless0  |   CHROME_REFRESH_TIME: 3600000,
browserless0  |   KEEP_ALIVE: true,
browserless0  |   DEFAULT_BLOCK_ADS: false,
browserless0  |   DEFAULT_HEADLESS: false,
browserless0  |   DEFAULT_LAUNCH_ARGS: [
browserless0  |     '--window-size=1920,1080',
browserless0  |     '--proxy-server=socks5://192.168.1.140:1078'
browserless0  |   ],
browserless0  |   DEFAULT_IGNORE_DEFAULT_ARGS: false,
browserless0  |   DEFAULT_IGNORE_HTTPS_ERRORS: true,
browserless0  |   DEFAULT_DUMPIO: false,
browserless0  |   DEFAULT_STEALTH: true,
browserless0  |   DEFAULT_USER_DATA_DIR: undefined,
browserless0  |   PREBOOT_CHROME: true,
browserless0  |   PREBOOT_QUANTITY: 0,
browserless0  |   PRINT_GET_STARTED_LINKS: true,
browserless0  |   PRINT_NETWORK_INFO: true,
browserless0  |   DEBUG: 'browserless*',
browserless0  |   DISABLED_FEATURES: [
browserless0  |     'downloadEndpoint',
browserless0  |     'functionEndpoint',
browserless0  |     'pdfEndpoint',
browserless0  |     'screencastEndpoint',
browserless0  |     'scrapeEndpoint',
browserless0  |     'statsEndpoint',
browserless0  |     'workspaces'
browserless0  |   ],
browserless0  |   ENABLE_CORS: true,
browserless0  |   ENABLE_API_GET: false,
browserless0  |   TOKEN: null,
browserless0  |   ENABLE_HEAP_DUMP: false,
browserless0  |   ALLOW_FILE_PROTOCOL: false,
browserless0  |   DISABLE_AUTO_SET_DOWNLOAD_BEHAVIOR: false,
browserless0  |   FUNCTION_BUILT_INS: [ 'url' ],
browserless0  |   FUNCTION_ENV_VARS: [],
browserless0  |   FUNCTION_ENABLE_INCOGNITO_MODE: true,
browserless0  |   FUNCTION_EXTERNALS: [ 'lighthouse', 'node-pdftk', 'sharp' ],
browserless0  |   WORKSPACE_DIR: '/usr/src/app/workspace',
browserless0  |   WORKSPACE_DELETE_EXPIRED: false,
browserless0  |   WORKSPACE_EXPIRE_DAYS: 30,
browserless0  |   FAILED_HEALTH_URL: null,
browserless0  |   QUEUE_ALERT_URL: null,
browserless0  |   REJECT_ALERT_URL: null,
browserless0  |   TIMEOUT_ALERT_URL: null,
browserless0  |   ERROR_ALERT_URL: null,
browserless0  |   SESSION_CHECK_FAIL_URL: null,
browserless0  |   PRE_REQUEST_HEALTH_CHECK: false,
browserless0  |   EXIT_ON_HEALTH_FAILURE: true,
browserless0  |   MAX_CPU_PERCENT: 99,
browserless0  |   MAX_MEMORY_PERCENT: 99,
browserless0  |   METRICS_JSON_PATH: null,
browserless0  |   HOST: '0.0.0.0',
browserless0  |   PORT: 3000,
browserless0  |   SOCKET_CLOSE_METHOD: 'http',
browserless0  |   PROXY_URL: undefined,
browserless0  |   MAX_PAYLOAD_SIZE: '5mb'
browserless0  | }
browserless0  | 2023-10-21T12:39:48.169Z browserless:server
browserless0  |
browserless0  | Running on port 3000
browserless0  |         Localhost        ws:localhost:3000
browserless0  |         Local network    ws:172.27.0.2:3000
browserless0  | 2023-10-21T12:39:48.169Z browserless:server
browserless0  | Get started at   https://www.browserless.io/docs/start
browserless0  | Get a license at         https://www.browserless.io/sign-up?type=commercial
browserless0  | Get support at   https://www.browserless.io/contact
browserless0  |
browserless0  | Happy coding!
browserless0  |
browserless0  | 2023-10-21T12:39:48.173Z browserless:system Starting chrome swarm: 1 chrome instances starting
browserless0  | 2023-10-21T12:39:48.174Z browserless:chrome-helper Launching Chrome with args: {
browserless0  |   "args": [
browserless0  |     "--no-sandbox",
browserless0  |     "--enable-logging",
browserless0  |     "--v1=1",
browserless0  |     "--disable-dev-shm-usage",
browserless0  |     "--no-first-run",
browserless0  |     "--window-size=1920,1080",
browserless0  |     "--proxy-server=socks5://192.168.1.140:1078",
browserless0  |     "--remote-debugging-port=41479",
browserless0  |     "--user-data-dir=/tmp/browserless-data-dir-0kOS81"
browserless0  |   ],
browserless0  |   "blockAds": false,
browserless0  |   "headless": false,
browserless0  |   "ignoreDefaultArgs": false,
browserless0  |   "ignoreHTTPSErrors": true,
browserless0  |   "pauseOnConnect": false,
browserless0  |   "userDataDir": "/tmp/browserless-data-dir-0kOS81",
browserless0  |   "playwright": false,
browserless0  |   "stealth": true,
browserless0  |   "meta": null,
browserless0  |   "executablePath": "/usr/bin/google-chrome",
browserless0  |   "handleSIGINT": false,
browserless0  |   "handleSIGTERM": false,
browserless0  |   "handleSIGHUP": false
browserless0  | }
browserless0  | 2023-10-21T12:39:48.556Z browserless:chrome-helper Chrome PID: 26
browserless0  | 2023-10-21T12:39:48.557Z browserless:chrome-helper Finding prior pages
browserless0  | 2023-10-21T12:39:48.659Z browserless:chrome-helper Found 1 pages
browserless0  | 2023-10-21T12:39:48.659Z browserless:chrome-helper Setting up page Unknown
browserless0  | 2023-10-21T12:39:48.659Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
browserless0  | 2023-10-21T12:39:48.660Z browserless:system Chrome launched 487ms
browserless0  | 2023-10-21T12:39:48.669Z browserless:chrome-helper Setting up file:// protocol request rejection
``` 

after that write a little script in node js : 
```javascript
const express = require('express');
const puppeteer = require('puppeteer');
//const fs = require('fs').promises;

const app = express();

app.get('/screenshot', async (req, res) => {
    console.log('Connecting....');
    browser = await puppeteer.connect({
            headless: false,
            browserWSEndpoint: 'ws://localhost:3000',
			
        });
	const page = await browser.newPage();
	
     await page.goto('https://monip.org');
	
	//Photo !
    const imageBuffer = await page.screenshot();
	await browser.close();

    res.set('Content-Type', 'image/jpeg');
    res.send(imageBuffer);
    console.log('Done :)');
});

app.listen(2000, () => {
    console.log('Listening on port 2000');
});
``` 

i start it : 
``` 
eliot@chrysapileradieux:~/browserless$ node app.js
Listening on port 2000
``` 

When i call it browserless crash T_T : 
``` 
browserless0  | 2023-10-21T12:42:25.610Z browserless:job 64WDCEGRDLC7LYCBJ1T4K63L7ICQWPA2: /: Inbound WebSocket request.
browserless0  | 2023-10-21T12:42:25.627Z browserless:hardware Checking overload status: CPU 1% Memory 4%
browserless0  | 2023-10-21T12:42:25.628Z browserless:job 64WDCEGRDLC7LYCBJ1T4K63L7ICQWPA2: Adding new job to queue.
browserless0  | 2023-10-21T12:42:25.628Z browserless:server Starting new job
browserless0  | 2023-10-21T12:42:25.628Z browserless:system Waiting pre-booted chrome instance
browserless0  | 2023-10-21T12:42:25.629Z browserless:job 64WDCEGRDLC7LYCBJ1T4K63L7ICQWPA2: Getting browser.
browserless0  | 2023-10-21T12:42:25.629Z browserless:system Got chrome instance
browserless0  | 2023-10-21T12:42:25.629Z browserless:job 64WDCEGRDLC7LYCBJ1T4K63L7ICQWPA2: Starting session.
browserless0  | 2023-10-21T12:42:25.629Z browserless:job 64WDCEGRDLC7LYCBJ1T4K63L7ICQWPA2: Proxying request to /devtools/browser route: ws://127.0.0.1:41479/devtools/browser/5816e3d1-59ff-4b43-b6b6-704a19f0fb25.
browserless0  | 2023-10-21T12:42:25.674Z browserless:chrome-helper Setting up page Unknown
browserless0  | 2023-10-21T12:42:25.674Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
browserless0  | 2023-10-21T12:42:25.676Z browserless:chrome-helper Setting up file:// protocol request rejection
browserless0  | 2023-10-21T12:42:25.891Z browserless:server 64WDCEGRDLC7LYCBJ1T4K63L7ICQWPA2: Recording successful stat and cleaning up.
browserless0  | 2023-10-21T12:42:25.891Z browserless:job 64WDCEGRDLC7LYCBJ1T4K63L7ICQWPA2: Cleaning up job
browserless0  | 2023-10-21T12:42:25.891Z browserless:job 64WDCEGRDLC7LYCBJ1T4K63L7ICQWPA2: Browser has been alive for 157335ms
browserless0  | 2023-10-21T12:42:25.891Z browserless:job 64WDCEGRDLC7LYCBJ1T4K63L7ICQWPA2: Pushing browser back into swarm, clearing pages
browserless0  | 2023-10-21T12:42:25.892Z browserless:server Current workload complete.
browserless0  | 2023-10-21T12:42:25.893Z browserless:job 64WDCEGRDLC7LYCBJ1T4K63L7ICQWPA2: Cleanup done, pushing into swarm.
browserless0  | Unhandled Rejection at: Promise {
browserless0  |   <rejected> TargetCloseError: Protocol error (Page.navigate): Target closed
browserless0  |       at CallbackRegistry.clear (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:139:36)
browserless0  |       at CdpCDPSession._onClosed (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:96:25)
browserless0  |       at Connection.onMessage (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:249:25)
browserless0  |       at WebSocket.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:52:32)
browserless0  |       at callListener (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)
browserless0  |       at WebSocket.onMessage (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:209:9)
browserless0  |       at WebSocket.emit (node:events:517:28)
browserless0  |       at Receiver.receiverOnMessage (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1192:20)
browserless0  |       at Receiver.emit (node:events:517:28)
browserless0  |       at Receiver.dataMessage (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/receiver.js:560:14) {
browserless0  |     cause: ProtocolError
browserless0  |         at <instance_members_initializer> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:42:14)
browserless0  |         at new Callback (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:46:16)
browserless0  |         at CallbackRegistry.create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:86:26)
browserless0  |         at Connection._rawSend (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:208:26)
browserless0  |         at CdpCDPSession.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:61:33)
browserless0  |         at navigate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:165:51)
browserless0  |         at CdpFrame.goto (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:143:17)
browserless0  |         at CdpFrame.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:108:27)
browserless0  |         at CdpPage.goto (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:696:43)
browserless0  |         at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:423:32)
browserless0  |   }
browserless0  | } reason: TargetCloseError: Protocol error (Page.navigate): Target closed
browserless0  |     at CallbackRegistry.clear (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:139:36)
browserless0  |     at CdpCDPSession._onClosed (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:96:25)
browserless0  |     at Connection.onMessage (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:249:25)
browserless0  |     at WebSocket.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:52:32)
browserless0  |     at callListener (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)
browserless0  |     at WebSocket.onMessage (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:209:9)
browserless0  |     at WebSocket.emit (node:events:517:28)
browserless0  |     at Receiver.receiverOnMessage (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1192:20)
browserless0  |     at Receiver.emit (node:events:517:28)
browserless0  |     at Receiver.dataMessage (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/receiver.js:560:14) {
browserless0  |   cause: ProtocolError
browserless0  |       at <instance_members_initializer> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:42:14)
browserless0  |       at new Callback (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:46:16)
browserless0  |       at CallbackRegistry.create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:86:26)
browserless0  |       at Connection._rawSend (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:208:26)
browserless0  |       at CdpCDPSession.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:61:33)
browserless0  |       at navigate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:165:51)
browserless0  |       at CdpFrame.goto (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:143:17)
browserless0  |       at CdpFrame.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:108:27)
browserless0  |       at CdpPage.goto (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:696:43)
browserless0  |       at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:423:32)
browserless0  | }
browserless0  | Unhandled Rejection at: Promise {
browserless0  |   <rejected> ProtocolError: Protocol error (Target.closeTarget): No target with given id found
browserless0  |       at <instance_members_initializer> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:42:14)
browserless0  |       at new Callback (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:46:16)
browserless0  |       at CallbackRegistry.create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:86:26)
browserless0  |       at Connection._rawSend (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:208:26)
browserless0  |       at Connection.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:202:21)
browserless0  |       at CdpPage.close (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:868:30)
browserless0  |       at /usr/src/app/build/puppeteer-provider.js:422:46
browserless0  |       at Array.forEach (<anonymous>)
browserless0  |       at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:422:23)
browserless0  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
browserless0  | } reason: ProtocolError: Protocol error (Target.closeTarget): No target with given id found
browserless0  |     at <instance_members_initializer> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:42:14)
browserless0  |     at new Callback (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:46:16)
browserless0  |     at CallbackRegistry.create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:86:26)
browserless0  |     at Connection._rawSend (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:208:26)
browserless0  |     at Connection.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:202:21)
browserless0  |     at CdpPage.close (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:868:30)
browserless0  |     at /usr/src/app/build/puppeteer-provider.js:422:46
browserless0  |     at Array.forEach (<anonymous>)
browserless0  |     at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:422:23)
browserless0  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
browserless0  | 2023-10-21T12:42:25.937Z browserless:chrome-helper Browser process 5816e3d1-59ff-4b43-b6b6-704a19f0fb25 has closed, cleaning up.
browserless0  | 2023-10-21T12:42:25.937Z browserless:chrome-helper Shutting down browser with close command
browserless0  | 2023-10-21T12:42:25.937Z browserless:chrome-helper Sending SIGKILL signal to browser process 26
browserless0  | 2023-10-21T12:42:25.943Z browserless:chrome-helper Removing temp data-dir /tmp/browserless-data-dir-0kOS81
browserless0  | 2023-10-21T12:42:25.960Z browserless:chrome-helper Temp dir /tmp/browserless-data-dir-0kOS81 removed successfully
browserless0  | 2023-10-21T12:42:26.937Z browserless:chrome-helper Garbage collecting and removing listeners
``` 

The docker node is a virtual machine : 
``` 
eliot@chrysapileradieux:~/browserless$ neofetch
       _,met$$$$$gg.          eliot@chrysapileradieux
    ,g$$$$$$$$$$$$$$$P.       -----------------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64
 ,$$P'              `$$$.     Host: VMware Virtual Platform None
',$$P       ,ggs.     `$$b:   Kernel: 5.10.0-26-amd64
`d$$'     ,$P"'   .    $$$    Uptime: 32 mins
 $$P      d$'     ,    $$P    Packages: 797 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4
 $$;      Y$b._   _,d$P'      Resolution: preferred
 Y$$.    `.`"Y$$$$P"'         Terminal: /dev/pts/0
 `$$b      "-.__              CPU: AMD Ryzen 7 5825U with Radeon Graphics (12) @ 1.996GHz
  `Y$$                        GPU: 00:0f.0 VMware SVGA II Adapter
   `Y$$.                      Memory: 1152MiB / 52210MiB
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""

eliot@chrysapileradieux:~/browserless$ docker -v
Docker version 24.0.6, build ed223bc
eliot@chrysapileradieux:~/browserless$ node -v
v18.18.2
eliot@chrysapileradieux:~/browserless$ cat package.json
{
  "dependencies": {
    "express": "^4.18.2",
    "got": "^13.0.0",
    "p-queue": "^7.4.1",
    "p-retry": "^6.1.0",
    "puppeteer": "^21.3.8"
  },

``` 

Any advise ? 
At first it worked fine but not anymore, I don't know why.

Thanks, Eliot

**Comment by joelgriffith** [comment]
Can you possibly try with the new v2 image, or at least confirm you're running the right puppeteer version in both your code and the browserless image?
