### ISSUE TITLE
Couldn't load route "/content" due to missing browser of "CDPChromium"

### ISSUE THREAD

**Issue by Adrianni** [browserless/browserless#3702]
I have pulled and installed npm package, when run test.sh or start browserless i get the following error:

Couldn't load route "/content" due to missing browser of "CDPChromium"

```
root@changedetection:/opt/browserless# systemctl status browserless
* browserless.service - browserless service
     Loaded: loaded (/etc/systemd/system/browserless.service; enabled; preset: enabled)
     Active: active (running) since Sun 2023-11-26 20:21:40 CET; 4min 12s ago
   Main PID: 1945 (start.sh)
      Tasks: 2 (limit: 18811)
     Memory: 27.3M
        CPU: 1.681s
     CGroup: /system.slice/browserless.service
             |-1945 /bin/bash /opt/browserless/start.sh
             `-1946 Xvfb :99 -screen 0 1920x1080x16 -nolisten tcp -nolisten unix

Nov 26 20:21:41 changedetection browserless[1948]: Unhandled Rejection at: Promise {
Nov 26 20:21:41 changedetection browserless[1948]:   <rejected> Error: Couldn't load route "/content" due to missing browser of "CDPChromium"
Nov 26 20:21:41 changedetection browserless[1948]:       at file:///opt/browserless/build/browserless.js:148:23
Nov 26 20:21:41 changedetection browserless[1948]:       at Array.forEach (<anonymous>)
Nov 26 20:21:41 changedetection browserless[1948]:       at Browserless.start (file:///opt/browserless/build/browserless.js:145:38)
Nov 26 20:21:41 changedetection browserless[1948]: } reason: Error: Couldn't load route "/content" due to missing browser of "CDPChromium"
Nov 26 20:21:41 changedetection browserless[1948]:     at file:///opt/browserless/build/browserless.js:148:23
Nov 26 20:21:41 changedetection browserless[1948]:     at Array.forEach (<anonymous>)
Nov 26 20:21:41 changedetection browserless[1948]:     at Browserless.start (file:///opt/browserless/build/browserless.js:145:38)
Nov 26 20:21:41 changedetection browserless[1948]: 2023-11-26T19:21:41.562Z browserless:index.js Process is finished, exiting
```

**Comment by andyMrtnzP** [comment]
I've seen this happening on dev, mostly on Windows, when Playwright can't find the executable... Do you still have the issue after you run `npm run install:dev`?

**Comment by joelgriffith** [comment]
We typically don't support bare-metal installs... have you tried to use the docker package?
