### ISSUE TITLE
TimeoutError from puppeteer without an option to increase it?

### ISSUE THREAD

**Issue by ronaldtb** [browserless/browserless#3865]
**Describe the bug**
I'm running into a `browserless:system TimeoutError: Timed out after waiting 30000ms` error using the latest docker image (`browserless/chrome:latest`) to generate a PDF from a large HTML file (5.6MB).

This while calling the `/pdf` endpoint with the following payload:
```json
{
  "html": "...",
  "safeMode": true,
  "options": {
    "displayHeaderFooter": true,
    "printBackground": true,
    "preferCSSPageSize": true,
    "landscape": true,
    "timeout": 600000
  },
  "gotoOptions": {
    "waitUntil": "networkidle0",
    "timeout": 600000
  },
  "addScriptTag": [],
  "addStyleTag": [],
  "cookies": [],
  "rejectRequestPattern": [],
  "rejectResourceTypes": [],
  "requestInterceptors": []
}
```

I also set the following environment variables:
```shell
CONNECTION_TIMEOUT: '60000'
MAX_PAYLOAD_SIZE: '10mb'
```

Is there a way to increase the timeout that is causing this issue?

**Additional context**
The complete error message is:
```
browserless:system TimeoutError: Timed out after waiting 30000ms
    at /usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:287:19
    at /usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:59978
    at f._next (/usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:11821)
    at t.next (/usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:6459)
    at t.<anonymous> (/usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:71381)
    at t._execute (/usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:28234)
    at t.execute (/usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:28057)
    at t.flush (/usr/src/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:32540)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) Issue launching Chrome, retrying 1 times.
```

**Comment by joelgriffith** [comment]
Could you please try the `chromium` variant? `ghcr.io/browserless/chromium`. Chrome is relatively new and _should_ work much the same, however some things are slower and more difficult for it.

See https://github.com/browserless/browserless/discussions/3859 for a bit more reference

**Comment by ronaldtb** [comment]
Thanks for the quick response @joelgriffith. It seems the `page.pdf()` call within puppeteer also supports a `timeout` option that needs to be set.

I work around the issue by manually calling puppeteer and providing the timeout to the `page.pdf()` call..

**Comment by kingp0dd** [comment]
I don't know if this is related, but I'm getting a Timeout error as well. 

```
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: AxiosHeaders {
      'content-type': 'text/plain; charset=UTF-8',
      date: 'Tue, 16 Apr 2024 01:12:05 GMT',
      connection: 'close',
      'transfer-encoding': 'chunked'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 200000,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [AxiosHeaders],
      method: 'post',
      url: 'http://browserless2:3000/screenshot',
      ...
     },
    data: 'TimeoutError: Navigation timeout of 30000 ms exceeded\n'
  }
```

docker compose:
```
  browserless2:
    container_name: browserless2
    hostname: browserless2
    image: ghcr.io/browserless/chromium:latest
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - TIMEOUT=900000
      - CONCURRENT=2
      - TOKEN=x
```
