### ISSUE TITLE
Cannot launch browser with multi:2.2

### ISSUE THREAD

**Issue by Aubermean** [browserless/browserless#3870]
Using v1 works fine, but when I use v2.2 (previous tags are not available...why?) I cannot launch a browser. I get an error in my client saying `Connection refused for "0.0.0.0" port 3000`. Even if I change the browserless port to something other than 3000, I still get that same error. Is it something to do with how proxification to CDP takes place?

```
 puppeteer-extra-plugin:base:stealth Initialized. +0ms
  puppeteer-extra plugin registered stealth +0ms
  browserless.io:limiter Concurrency: 10 queue: 10 timeout: 30000ms +0ms
  browserless.io:index
  browserless.io:index ---------------------------------------------------------
  browserless.io:index | browserless.io
  browserless.io:index | To read documentation and more, load in your browser:
  browserless.io:index |
  browserless.io:index | http://0.0.0.0:3000/docs
  browserless.io:index ---------------------------------------------------------
  browserless.io:index
  browserless.io:index
  browserless.io:index █▓▒
  browserless.io:index ████▒
  browserless.io:index ████▒
  browserless.io:index ████▒   ▒██▓▒
  browserless.io:index ████▒   ▒████
  browserless.io:index ████▒   ▒████
  browserless.io:index ████▒   ▒████
  browserless.io:index ████▒   ▒████
  browserless.io:index ████▒   ▒████
  browserless.io:index ████▒   ▒██████▓▒
  browserless.io:index ████▒   ▒██████████▒
  browserless.io:index ████▒   ▒██████▓████
  browserless.io:index ████▒   ▒█▓▓▒  ▒████
  browserless.io:index ████▒          ▒████
  browserless.io:index ████▒       ▒▓██████
  browserless.io:index ████▒   ▒▓████████▓▒
  browserless.io:index ████▓▓████████▓▒
  browserless.io:index ██████████▓▒
  browserless.io:index   ▓███▓▒
  browserless.io:index
  browserless.io:index  +0ms
  browserless.io:index Running as user "blessuser" +0ms
  browserless.io:index Starting import of HTTP Routes +0ms
  browserless.io:index Starting import of WebSocket Routes +71ms
  browserless.io:router:verbose Registering HTTP POST /content,/chromium/content +0ms
  browserless.io:router:verbose Registering HTTP POST /download,/chromium/download +0ms
  browserless.io:router:verbose Registering HTTP POST /function,/chromium/function +0ms
  browserless.io:router:verbose Registering HTTP GET /json/list +0ms
  browserless.io:router:verbose Registering HTTP PUT /json/new +1ms
  browserless.io:router:verbose Registering HTTP GET /json/protocol +0ms
  browserless.io:router:verbose Registering HTTP GET /json/version +0ms
  browserless.io:router:verbose Registering HTTP POST /pdf,/chromium/pdf +0ms
  browserless.io:router:verbose Registering HTTP POST /performance,/chromium/performance +0ms
  browserless.io:router:verbose Registering HTTP POST /scrape,/chromium/scrape +0ms
  browserless.io:router:verbose Registering HTTP POST /screenshot,/chromium/screenshot +0ms
  browserless.io:router:verbose Registering HTTP GET /config +0ms
  browserless.io:router:verbose Registering HTTP GET /metrics/total +1ms
  browserless.io:router:verbose Registering HTTP GET /metrics +0ms
  browserless.io:router:verbose Registering HTTP GET /sessions +0ms
  browserless.io:router:verbose Registering HTTP GET / +0ms
  browserless.io:router:verbose Registering WebSocket "/devtools/browser/*" +0ms
  browserless.io:router:verbose Registering WebSocket "?(/),/chromium" +0ms
  browserless.io:router:verbose Registering WebSocket "/devtools/page/*" +0ms
  browserless.io:router:verbose Registering WebSocket "/playwright/chromium,/chromium/playwright" +0ms
  browserless.io:router:verbose Registering WebSocket "/playwright/firefox,/firefox/playwright" +0ms
  browserless.io:router:verbose Registering WebSocket "/playwright/webkit,/webkit/playwright" +0ms
  browserless.io:index Imported and validated all route files, starting up server. +21ms
  browserless.io:server Server instantiated with host "0.0.0.0" on port "3000" using token "null" +0ms
  browserless.io:server HTTP Server is starting +0ms
  browserless.io:server HTTP Server is listening on http://0.0.0.0:3000
  browserless.io:server Use http://0.0.0.0:3000 for API and connect calls +2ms
  browserless.io:index Starting metrics collection. +4ms
  browserless.io:server:verbose Handling inbound HTTP request on "GET: /json/version" +0ms
  browserless.io:server:verbose Found matching HTTP route handler "/json/version" +7ms
  browserless.io:server:verbose Authorizing HTTP request to "/json/version" +0ms
  browserless.io:browser-manager Launching Chromium to generate /json/version results +0ms
  browserless.io:browsers:chromium:cdp Starting new browser instance +0ms
  browserless.io:browsers:chromium:cdp Got open port 46053 +2ms
  browserless.io:browsers:chromium:cdp {
  browserless.io:browsers:chromium:cdp   args: [ '--remote-debugging-port=46053', '--no-sandbox' ],
  browserless.io:browsers:chromium:cdp   executablePath: '/usr/local/bin/playwright-browsers/chromium-1097/chrome-linux/chrome'
  browserless.io:browsers:chromium:cdp } Launching CDP Handler +0ms
  puppeteer:browsers:launcher Launching /usr/local/bin/playwright-browsers/chromium-1097/chrome-linux/chrome --allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-field-trial-config --disable-hang-monitor --disable-infobars --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-search-engine-choice-screen --disable-sync --enable-automation --export-tagged-pdf --generate-pdf-document-outline --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --disable-features=Translate,AcceptCHFrame,MediaRouter,OptimizationHints,ProcessPerSiteUpToMainFrameThreshold --enable-features=NetworkServiceInProcess2 --headless=new --hide-scrollbars --mute-audio about:blank --remote-debugging-port=46053 --no-sandbox --user-data-dir=/tmp/puppeteer_dev_chrome_profile-8XZYxU {
  detached: true,
  env: { PUPPETEER_SKIP_DOWNLOAD: 'true' },
  stdio: [ 'pipe', 'ignore', 'pipe' ]
} +0ms
  puppeteer:browsers:launcher Launched 22 +11ms
  puppeteer:protocol:SEND ► [
  puppeteer:protocol:SEND ►   '{"method":"Target.setDiscoverTargets","params":{"discover":true,"filter":[{}]},"id":1}'
  puppeteer:protocol:SEND ► ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"3806b1b1-0f35-4472-bff4-96a7237a6bde","type":"browser","title":"","url":"","attached":true,"canAccessOpener":false}}}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"AC1BF594D94F939BE0B81834CFEDBFC4","type":"page","title":"","url":"about:blank","attached":false,"canAccessOpener":false,"browserContextId":"7D2F9D0FCE32B827CD26DDAFF41B2052"}}}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"DEE3FF873561C39AFCFB904ABB6826BE","type":"tab","title":"","url":"about:blank","attached":false,"canAccessOpener":false,"browserContextId":"7D2F9D0FCE32B827CD26DDAFF41B2052"}}}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [ '{"id":1,"result":{}}' ] +0ms
  puppeteer:protocol:SEND ► [
  puppeteer:protocol:SEND ►   '{"method":"Target.setAutoAttach","params":{"waitForDebuggerOnStart":true,"flatten":true,"autoAttach":true,"filter":[{"type":"page","exclude":true},{}]},"id":2}'
  puppeteer:protocol:SEND ► ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"AC1BF594D94F939BE0B81834CFEDBFC4","type":"page","title":"about:blank","url":"about:blank","attached":false,"canAccessOpener":false,"browserContextId":"7D2F9D0FCE32B827CD26DDAFF41B2052"}}}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"DEE3FF873561C39AFCFB904ABB6826BE","type":"tab","title":"about:blank","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"7D2F9D0FCE32B827CD26DDAFF41B2052"}}}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Target.attachedToTarget","params":{"sessionId":"BBE420EB6D41C3AF6840E4B8402C18FE","targetInfo":{"targetId":"DEE3FF873561C39AFCFB904ABB6826BE","type":"tab","title":"about:blank","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"7D2F9D0FCE32B827CD26DDAFF41B2052"},"waitingForDebugger":false}}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:SEND ► [
  puppeteer:protocol:SEND ►   '{"method":"Target.setAutoAttach","params":{"waitForDebuggerOnStart":true,"flatten":true,"autoAttach":true,"filter":[{}]},"id":1,"sessionId":"BBE420EB6D41C3AF6840E4B8402C18FE"}'
  puppeteer:protocol:SEND ► ] +0ms
  puppeteer:protocol:SEND ► [
  puppeteer:protocol:SEND ►   '{"method":"Runtime.runIfWaitingForDebugger","id":2,"sessionId":"BBE420EB6D41C3AF6840E4B8402C18FE"}'
  puppeteer:protocol:SEND ► ] +0ms
  puppeteer:protocol:RECV ◀ [ '{"id":2,"result":{}}' ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"AC1BF594D94F939BE0B81834CFEDBFC4","type":"page","title":"about:blank","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"7D2F9D0FCE32B827CD26DDAFF41B2052"}}}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Target.attachedToTarget","params":{"sessionId":"AE3E33B49A053628BB1C64383273B4AD","targetInfo":{"targetId":"AC1BF594D94F939BE0B81834CFEDBFC4","type":"page","title":"about:blank","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"7D2F9D0FCE32B827CD26DDAFF41B2052"},"waitingForDebugger":false},"sessionId":"BBE420EB6D41C3AF6840E4B8402C18FE"}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:SEND ► [
  puppeteer:protocol:SEND ►   '{"method":"Target.setAutoAttach","params":{"waitForDebuggerOnStart":true,"flatten":true,"autoAttach":true,"filter":[{}]},"id":1,"sessionId":"AE3E33B49A053628BB1C64383273B4AD"}'
  puppeteer:protocol:SEND ► ] +0ms
  puppeteer:protocol:SEND ► [
  puppeteer:protocol:SEND ►   '{"method":"Runtime.runIfWaitingForDebugger","id":2,"sessionId":"AE3E33B49A053628BB1C64383273B4AD"}'
  puppeteer:protocol:SEND ► ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"id":1,"result":{},"sessionId":"BBE420EB6D41C3AF6840E4B8402C18FE"}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"id":2,"result":{},"sessionId":"BBE420EB6D41C3AF6840E4B8402C18FE"}'
  puppeteer:protocol:RECV ◀ ] +0ms
  browserless.io:browsers:chromium:cdp Browser is running on ws://127.0.0.1:46053/devtools/browser/4d7cfd7c-b07b-4d1c-bd02-7ee44223ad40 +501ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"id":1,"result":{},"sessionId":"AE3E33B49A053628BB1C64383273B4AD"}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"id":2,"result":{},"sessionId":"AE3E33B49A053628BB1C64383273B4AD"}'
  puppeteer:protocol:RECV ◀ ] +0ms
  browserless.io:browsers:chromium:cdp Closing browser process and all listeners +47ms
  puppeteer:protocol:SEND ► [ '{"method":"Browser.close","id":3}' ] +0ms
  browserless.io:server:verbose HTTP connection complete +558ms
  puppeteer:error [
  puppeteer:error   TargetCloseError: Protocol error (Browser.close): Target closed
  puppeteer:error       at CallbackRegistry.clear (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:72:36)
  puppeteer:error       at #onClose (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:152:25)
  puppeteer:error       at Connection.dispose (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:160:22)
  puppeteer:error       at CdpBrowser.disconnect (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:225:26)
  puppeteer:error       at CdpBrowser.close (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:221:20)
  puppeteer:error       at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  puppeteer:error     cause: ProtocolError
  puppeteer:error         at <instance_members_initializer> (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:92:14)
  puppeteer:error         at new Callback (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:96:16)
  puppeteer:error         at CallbackRegistry.create (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
  puppeteer:error         at Connection._rawSend (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:77:26)
  puppeteer:error         at Connection.send (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:71:21)
  puppeteer:error         at Connection.closeBrowser (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:92:20)
  puppeteer:error         at ChromeLauncher.closeBrowser (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:138:37)
  puppeteer:error         at browserCloseCallback (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:70:24)
  puppeteer:error         at CdpBrowser.close (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:220:35)
  puppeteer:error         at [nodejs.dispose] (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/api/Browser.js:130:26)
  puppeteer:error   }
  puppeteer:error ] +0ms
  puppeteer:browsers:launcher Browser process 22 onExit +617ms
```

**Comment by Aubermean** [comment]
chrome image is not yet built for arm, so I am unable to try that. Please try to retain older tags, I am unable to try the versions prior to 2.2 for further testing.

**Comment by joelgriffith** [comment]
Can you share what version of puppeteer you're using and that code as well? We have a lot of regression and E2E tests that verify everything before it goes out, so there must be something else...

**Comment by Aubermean** [comment]
The issue it seems is in ferrum, and how it overrides the ws_url with the ws url in /json/version.

https://github.com/rubycdp/ferrum/pull/447
