### ISSUE TITLE
TIMEOUT param ignored?

### ISSUE THREAD

**Issue by matheusjardimb** [browserless/browserless#4096]
I'm trying to generate a PDF file from a huge web page (about 1k A4 pages) but I keep getting the following error despite setting a much higher timeout limit.

```
2024-06-10T03:14:35.696403678Z   browserless.io:router:trace  HTTP Request handler has finished. +52s
2024-06-10T03:14:35.696403678Z   browserless.io:browser-manager:info  0 Client(s) are currently connected, Keep-until: 0 +2m
2024-06-10T03:14:35.696408174Z   browserless.io:browser-manager:info  Closing browser session +0ms
2024-06-10T03:14:35.696411290Z   browserless.io:browser-manager:info  Deleting "/tmp/browserless-data-dirs/browserless-data-dir-f8c4996a-45c0-4fc1-8361-4845701a66b0" user-data-dir and session from memory +0ms
2024-06-10T03:14:35.696429397Z   browserless.io:ChromiumPDFPostRoute:info 172.18.0.6 Closing ChromiumCDP process and all listeners +52s
2024-06-10T03:14:35.697006353Z   puppeteer:protocol:SEND ► [ '{"method":"Browser.close","id":4}' ] +0ms
2024-06-10T03:14:35.706575736Z   browserless.io:limiter:info  (Running: 0, Pending: 0) All jobs complete.  +53s
2024-06-10T03:14:35.706612090Z   browserless.io:limiter:info  Recording failed stat, cleaning up: "TimeoutError: Timed out after waiting 30000ms" +0ms
2024-06-10T03:14:35.706615766Z Issue calling error hook: "TypeError: Invalid URL". Did you set a working ERROR_ALERT_URL env variable?
2024-06-10T03:14:35.706618600Z   puppeteer:error [
2024-06-10T03:14:35.706621006Z   puppeteer:error   TargetCloseError: Protocol error (Browser.close): Target closed
2024-06-10T03:14:35.706623710Z   puppeteer:error       at CallbackRegistry.clear (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69:36)
2024-06-10T03:14:35.706627009Z   puppeteer:error       at #onClose (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:160:25)
2024-06-10T03:14:35.706629817Z   puppeteer:error       at Connection.dispose (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:168:22)
2024-06-10T03:14:35.706632795Z   puppeteer:error       at CdpBrowser.disconnect (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:227:26)
2024-06-10T03:14:35.706635583Z   puppeteer:error       at CdpBrowser.close (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:223:20) {
2024-06-10T03:14:35.706638676Z   puppeteer:error     cause: ProtocolError
2024-06-10T03:14:35.706641132Z   puppeteer:error         at <instance_members_initializer> (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
2024-06-10T03:14:35.706644084Z   puppeteer:error         at new Callback (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
2024-06-10T03:14:35.706646934Z   puppeteer:error         at CallbackRegistry.create (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
2024-06-10T03:14:35.706651220Z   puppeteer:error         at Connection._rawSend (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:85:26)
2024-06-10T03:14:35.706668644Z   puppeteer:error         at Connection.send (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:78:21)
2024-06-10T03:14:35.706671672Z   puppeteer:error         at Connection.closeBrowser (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:100:20)
2024-06-10T03:14:35.706674566Z   puppeteer:error         at ChromeLauncher.closeBrowser (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:148:37)
2024-06-10T03:14:35.706677468Z   puppeteer:error         at browserCloseCallback (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:80:24)
2024-06-10T03:14:35.706680180Z   puppeteer:error         at CdpBrowser.close (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:222:35)
2024-06-10T03:14:35.706682842Z   puppeteer:error         at [nodejs.dispose] (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/api/Browser.js:131:30)
2024-06-10T03:14:35.706685601Z   puppeteer:error   }
2024-06-10T03:14:35.706687957Z   puppeteer:error ] +0ms
2024-06-10T03:14:35.706690412Z   puppeteer:browsers:launcher Trying to kill 132 +53s
2024-06-10T03:14:35.706692909Z   puppeteer:browsers:launcher Browser process 132 exists +0ms
2024-06-10T03:14:35.713113706Z   browserless.io:router:trace  Response has been written, resolving +16ms
2024-06-10T03:14:35.713597396Z   browserless.io:browser-manager:info  Deleting data directory "/tmp/browserless-data-dirs/browserless-data-dir-f8c4996a-45c0-4fc1-8361-4845701a66b0" +17ms
2024-06-10T03:14:35.750518263Z   puppeteer:browsers:launcher Browser process 132 onExit +44ms
2024-06-10T03:14:58.712740972Z   browserless.io:index:info  Current period usage: {"date":1717989298712,"error":2,"maxConcurrent":1,"maxTime":52593,"meanTime":30572,"minTime":8551,"rejected":0,"successful":0,"timedout":0,"totalTime":61144,"units":3} +5m
2024-06-10T03:14:58.712781805Z   browserless.io:index:info  Saving metrics to "/tmp/browserless-metrics.json" +0ms

```

I'm using browserless like this:

```
  chrome:
    image: ghcr.io/browserless/chromium:v2.12.0
    container_name: my_chrome
    environment:
      TZ: 'America/Sao_Paulo'
      CURRENT: 10
      TIMEOUT: 900000
      QUEUED: 100
      DEBUG: '*'
    ports:
      - '3000:3000'
```

My server takes about 60s to render all the HTML file, but the timeout I've set should've been 900s (15min), not the 30s that appear in the logs. The whole job runs as an async task, so I'm not worrying about how long it takes, assuming it successfully generates the PDF file.

**Comment by douglasmiranda** [comment]
Timeout issues with puppeteer and/or browserless are quite common unfortunately, so I'm gathering info about it and compiling in this gist (https://gist.github.com/douglasmiranda/ce242e6025513c5e975c176709d1343b) if you want, check it out and see if something there works for you.

**Comment by joelgriffith** [comment]
I'd refer to douglasmiranda's comment as it's true: puppeteer has general timers for just about every API call that _our_ timeout doesn't effect. The Browserless timeout is simply a total-session timer to prevent things from never closing at all, and is pivotal part of how our sessions work.
