### ISSUE TITLE
arm64 pdf error

### ISSUE THREAD

**Issue by lscool66** [browserless/browserless#4364]
browserless.io:server:trace  Handling inbound HTTP request on "POST: /pdf?token=6R0W53R135510" +49s
  browserless.io:server:trace  Found matching HTTP route handler "/pdf?(/),/chromium/pdf?(/)" +3ms
  browserless.io:server:trace  Authorizing HTTP request to "/pdf?token=6R0W53R135510" +0ms
  browserless.io:server:trace  Validating route query-params with QUERY schema +0ms
  browserless.io:server:trace  Validating route payload with BODY schema +8ms
WARNING: schema missing a 'type' or '$ref' or 'enum':
{}
  browserless.io:limiter:info  (Running: 0, Pending: 0) Adding to queue, max time allowed is 1,800,000ms  +15s
  browserless.io:limiter:info  (Running: 1, Pending: 0) Starting new job  +1ms
  browserless.io:ChromiumPDFPostRoute:info 10.9.247.89 Starting new ChromiumCDP instance +0ms
  browserless.io:ChromiumPDFPostRoute:info 10.9.247.89 ChromiumCDP got open port 41195 +1ms
  browserless.io:ChromiumPDFPostRoute:info 10.9.247.89 {
  args: [
    '--remote-debugging-port=41195',
    '--no-sandbox',
    '--user-data-dir=/tmp/browserless-data-dirs/browserless-data-dir-51c14bd7-21bf-4fdf-a4d6-2bbfe8e28b4c'
  ],
  executablePath: '/usr/local/bin/playwright-browsers/chromium-1140/chrome-linux/chrome'
} Launching ChromiumCDP Handler +0ms
  browserless.io:ChromiumPDFPostRoute:info 10.9.247.89 ChromiumCDP is running on ws://127.0.0.1:41195/devtools/browser/0b7c0383-a1c9-4ea5-999e-b9dc3b89838b +323ms
  browserless.io:router:trace  Running found HTTP handler. +15s
  browserless.io:ChromiumPDFPostRoute:info 10.9.247.89 PDF API invoked with body: {
  html: '<h1>Hello World!</h1>',
  options: { displayHeaderFooter: true, printBackground: false, format: 'A4' }
} +0ms
  browserless.io:ChromiumPDFPostRoute:trace 10.9.247.89 Setting up file:// protocol request rejection +0ms
  browserless.io:router:trace  HTTP Request handler has finished. +35s
  browserless.io:browser-manager:info  0 Client(s) are currently connected, Keep-until: 0 +50s
  browserless.io:browser-manager:info  Closing browser session +0ms
  browserless.io:browser-manager:info  Deleting "/tmp/browserless-data-dirs/browserless-data-dir-51c14bd7-21bf-4fdf-a4d6-2bbfe8e28b4c" user-data-dir and session from memory +0ms
  browserless.io:ChromiumPDFPostRoute:info 10.9.247.89 Closing ChromiumCDP process and all listeners +35s
  browserless.io:limiter:error  Error: Requesting main frame too early!
    at assert (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:15:15)
    at FrameManager.mainFrame (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/FrameManager.js:201:9)
    at CdpPage.mainFrame (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:390:35)
    at CdpPage.setContent (file:///usr/src/app/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:559:24)
    at ChromiumPDFPostRoute.handler (file:///usr/src/app/build/shared/pdf.http.js:72:36)
    at async file:///usr/src/app/build/router.js:60:28
    at async bound (file:///usr/src/app/build/limiter.js:136:36) +50s
  browserless.io:limiter:info  Recording failed stat, cleaning up: "Error: Requesting main frame too early!" +36s
Issue calling error hook: "TypeError: Invalid URL". Did you set a working ERROR_ALERT_URL env variable?
  browserless.io:limiter:info  (Running: 0, Pending: 0) All jobs complete.  +0ms
  browserless.io:router:trace  Response has been written, resolving +1ms
  browserless.io:browser-manager:info  Deleting data directory "/tmp/browserless-data-dirs/browserless-data-dir-51c14bd7-21bf-4fdf-a4d6-2bbfe8e28b4c" +3ms

**Comment by joelgriffith** [comment]
Do you have a sample cURL or POST body to reproduce this with?
