### ISSUE TITLE
Different mount points error - EISDIR: illegal operation on a directory, copyfile '/tmp/uBlock0.chromium' -> '/mnt/data/browserless/extensions/ublock'

### ISSUE THREAD

**Issue by ray-magini** [browserless/browserless#4372]
**Describe the bug**
When having the browserless source and install folder on an extra mount point and the /tmp folder on another, the `npm run build` fails with `Error: EISDIR: illegal operation on a directory, copyfile '/tmp/uBlock0.chromium' -> '/mnt/data/browserless/extensions/ublock'`

**To Reproduce**
* Clone the repository
```
myhost:/mnt/data# git clone https://github.com/browserless/browserless
Cloning into 'browserless'...
remote: Enumerating objects: 23704, done.
remote: Counting objects: 100% (220/220), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 23704 (delta 142), reused 199 (delta 126), pack-reused 23484 (from 1)
Receiving objects: 100% (23704/23704), 97.83 MiB | 24.94 MiB/s, done.
Resolving deltas: 100% (17618/17618), done.
```
* npm install
```
myhost:/mnt/data/browserless# npm install
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to c                                                                                                                                                                oalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 489 packages, and audited 490 packages in 10s

94 packages are looking for funding
  run `npm fund` for details

3 low severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
* npm run build
```
myhost:/mnt/data/browserless# npm run build

> @browserless.io/browserless@2.22.0 build
> npm run clean && npm run build:ts && npm run install:adblock && npm run build:schemas && npm run build:devtools && npm run build:openapi


> @browserless.io/browserless@2.22.0 clean
> node scripts/clean.js


> @browserless.io/browserless@2.22.0 build:ts
> tsc


> @browserless.io/browserless@2.22.0 install:adblock
> node scripts/install-adblock.js

node:internal/fs/promises:623
  return await PromisePrototypeThen(
         ^

Error: EISDIR: illegal operation on a directory, copyfile '/tmp/uBlock0.chromium' -> '/mnt/data/browserless/extensions/ublock'
    at async Object.copyFile (node:internal/fs/promises:623:10)
    at async _moveFile (file:///mnt/data/browserless/node_modules/move-file/index.js:50:4)
    at async file:///mnt/data/browserless/scripts/install-adblock.js:41:3 {
  errno: -21,
  code: 'EISDIR',
  syscall: 'copyfile',
  path: '/tmp/uBlock0.chromium',
  dest: '/mnt/data/browserless/extensions/ublock'
}

Node.js v20.18.0

```

**Reference**
```
myhost:/mnt/data/browserless# ls -al /tmp/uBlock0.chromium
total 400
drwxr-xr-x  9 root root   4096 Oct 24 14:44 .
drwxrwxrwt 16 root root 204800 Oct 24 15:50 ..
-rw-r--r--  1 root root   3726 Oct 24 15:42 1p-filters.html
-rw-r--r--  1 root root   6672 Oct 24 15:42 3p-filters.html
-rw-r--r--  1 root root   4843 Oct 24 15:42 about.html
-rw-r--r--  1 root root   1691 Oct 24 15:42 advanced-settings.html
drwxr-xr-x  5 root root   4096 Oct 24 14:44 assets
-rw-r--r--  1 root root   2159 Oct 24 15:42 asset-viewer.html
-rw-r--r--  1 root root    269 Oct 24 15:42 background.html
-rw-r--r--  1 root root   1204 Oct 24 15:42 cloud-ui.html
-rw-r--r--  1 root root   2222 Oct 24 15:42 code-viewer.html
drwxr-xr-x  4 root root   4096 Oct 24 14:44 css
-rw-r--r--  1 root root   2630 Oct 24 15:42 dashboard.html
-rw-r--r--  1 root root   3076 Oct 24 15:42 devtools.html
-rw-r--r--  1 root root   2682 Oct 24 15:42 document-blocked.html
-rw-r--r--  1 root root   3634 Oct 24 15:42 dyna-rules.html
drwxr-xr-x  4 root root   4096 Oct 24 14:44 img
-rw-r--r--  1 root root    155 Oct 24 15:42 is-webrtc-supported.html
drwxr-xr-x  5 root root   4096 Oct 24 14:44 js
drwxr-xr-x 10 root root   4096 Oct 24 14:44 lib
-rw-r--r--  1 root root  35126 Oct 24 15:42 LICENSE.txt
drwxr-xr-x 74 root root   4096 Oct 24 14:44 _locales
-rw-r--r--  1 root root  16563 Oct 24 15:42 logger-ui.html
-rw-r--r--  1 root root   2312 Oct 24 15:42 managed_storage.json
-rw-r--r--  1 root root   2763 Oct 24 15:42 manifest.json
-rw-r--r--  1 root root    851 Oct 24 15:42 no-dashboard.html
-rw-r--r--  1 root root   9148 Oct 24 15:42 popup-fenix.html
-rw-r--r--  1 root root  10363 Oct 24 15:42 settings.html
-rw-r--r--  1 root root   5731 Oct 24 15:42 support.html
drwxr-xr-x  2 root root   4096 Oct 24 14:44 web_accessible_resources
-rw-r--r--  1 root root   2779 Oct 24 15:42 whitelist.html

```
```
myhost:/mnt/data/browserless# mount |grep -E "sda|sdb"
/dev/sdb3 on / type ext4 (rw,relatime,errors=remount-ro)
/dev/sdb2 on /boot type ext4 (rw,noatime)
/dev/sda1 on /mnt/data type ext4 (rw,relatime)

```

**Environment**
- OS: Debian 12 with the latest updates
- Nodejs: node-jquery (3.6.1+dfsg+~3.5.14-1), node-mime (2.5.0+dfsg+~cs3.90.0-1), nodejs (20.18.0-1nodesource1)
- NPM: 10.8.2

**Additional context**
* As a workaround, does someone know how to set the /tmp folder to a different path (on the same mount point as the install) when using `npm run build`?

Thanks,
Dirk

**Comment by dertuxmalwieder** [comment]
Confirmed on openSUSE Tumbleweed.

**Comment by joelgriffith** [comment]
We primarily use `import { tmpdir } from 'os';` to insulate ourselves from instances like this. Maybe there's a way to configure this as an environment variable in NodeJS?
